# Generated by Django 4.0.3 on 2022-03-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraitem',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='extra_id',
            new_name='extra_item',
        ),
    ]
