# Generated by Django 4.0.3 on 2022-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emess', '0002_rename_meal_id_extraitem_meal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messadmin',
            name='hashpwd',
            field=models.CharField(default='0', max_length=96),
        ),
        migrations.AddField(
            model_name='student',
            name='hashpwd',
            field=models.CharField(default='0', max_length=96),
        ),
    ]
