# Generated by Django 4.0.3 on 2022-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emess', '0003_messadmin_hashpwd_student_hashpwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_hall',
            field=models.IntegerField(),
        ),
    ]
